export {default as HomePage } from './HomePage'
export {default as CategoryViewPage } from './CategoryViewPage'
export {default as SearchViewPage } from './SearchViewPage'
export {default as ProductPage } from './ProductPage'
export {default as MobileSearchPage } from './MobileSearchPage'
export {default as CartPage } from './CartPage'