export const categoriesData = [
    {
        id:1,
        image:"https://i.ibb.co/n1qXG8J/1.png",
        title:"T-SHIRTS"
    },
    {
        id:2,
        image:"https://i.ibb.co/jJYnL0V/2.png",
        title:"CASUAL-SHIRTS"
    },
    {
        id:3,
        image:"https://i.ibb.co/GWrzZnk/3.png",
        title:"CASUAL-TROUSERS"
    },
    {
        id:4,
        image:"https://i.ibb.co/5T22QVL/4.png",
        title:"FORMAL-SHIRTS"
    },
    {
        id:5,
        image:"https://i.ibb.co/yR23kR7/5.png",
        title:"FORMAL-TROUSERS"
    },
    {
        id:6,
        image:"https://i.ibb.co/q9n5BTx/1.png",
        title:"JACKETS"
    },
    {
        id:7,
        image:"https://i.ibb.co/HGCBgP3/7.png",
        title:"CASUAL SHOES"
    },
    {
        id:8,
        image:"https://i.ibb.co/2YG7gtz/8.png",
        title:"FORMAL SHOES"
    },
]